### PR TITLE
ui_imrovement

### PR DESCRIPTION
**Pull request by MayankGeek**

### CODE REVIEW

**Comment by grapheo12** [comment]
In `iqps/conf/app.env` change mode to `dev`.

**Comment by grapheo12** [comment]
Then restart the application

**Comment by MayankGeek** [comment]
Nope, It's not working.

**Comment by grapheo12** [comment]
Then do this: Stop the application. Run `docker-compose run python manage.py collectstatic` Then restart the application.

**Comment by MayankGeek** [comment]
mayank@mayank-80u6:~/iqps/iqps$ docker-compose run python manage.py collectstatic
ERROR: No such service: python

**Comment by MayankGeek** [comment]
Tried with Sudo and changing python to python3 it shows the same error

**Comment by grapheo12** [comment]
Sorry! `docker-compose run web python manage.py collectstatic` My bad!

**Comment by MayankGeek** [comment]
It worked but I need to run the command every time I am making a change to the CSS.

**Comment by grapheo12** [comment]
Yeah that you have to do sadly.
Or, in place of `docker-compose up`, you can run
`docker-compose run web python manage.py runserver 0.0.0.0:80`
to see instant changes on reload.

**Comment by grapheo12** [comment]
@MayankGeek Please provide screenshots of the changes.

**Comment by MayankGeek** [comment]
sudo docker-compose up is not working waited for 5 minutes and it was just hanging. No output at all.

**Comment by grapheo12** [comment]
Make sure another instance of the app is not running. Otherwise, I can't really say anything.

**Comment by MayankGeek** [comment]
I am again installing the project locally but getting this error
Step 4/4 : COPY ./bitap.so /usr/lib/mysql/plugin/bitap.so
ERROR: Service 'db' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder544391725/bitap.so: no such file or directory
Please help

**Comment by grapheo12** [comment]
@MayankGeek Please run `make` inside the `mariadb-udf-docker` folder. Get back to me if you have any problems.

**Comment by grapheo12** [comment]
This can be closed now safely I believe.

**Pull request closed without merging**
