### PR TITLE
Login utility

### PR DESCRIPTION
**Pull request by shobhit10058**
concerns issue #32.
some initial changes for including the register user options. 
Changes -
1. A non-authenticated user can only see the search options and the login page which can include the link to the register page.
2. The register page has the nav bar included with it for easy navigation.
3. An authenticated user can see all the initial tabs like request paper, upload paper , search, and logout.
4. The home button was included so that user can easily navigate to search options after clicking other tabs
5. If a non-authenticated user tries to user report, upload or request options by changing the URL he/she is redirected to home

### CODE REVIEW

**Comment by grapheo12** [comment]
@shobhit10058 Looks good! Just create a variable in `app.env` called `LOGIN_REQUIRED=True`, and make your templates so that if this variable is `True` then only your changes show up, otherwise the old website remains.

**Comment by grapheo12** [comment]
And yes! The Home button is unnecessary. The `MFQP` logo on the left redirects to the homepage.

**Comment by shobhit10058** [comment]
oh I did not knew about mfqp button.

**Comment by shobhit10058** [comment]
after login the old website is only there just a home button is extra I will remove it. Do I need to add that variable?

**Comment by shobhit10058** [comment]
after login
image

**Comment by shobhit10058** [comment]
oh, I think you want that the admin has privilege then that for him login will be required or not by default for accessing those options

**Comment by grapheo12** [comment]
No, I meant, this login feature should be a configurable option. The system admin might want to switch on/off as per requirements.
Remember, we are targetting users from different colleges, not just ours. So it will be good to have options.

**Comment by grapheo12** [comment]
Also, we had had quite a debate on this issue in MetaKGP. It's best to keep both.

**Comment by shobhit10058** [comment]
should I remove the app.env file here, I kept it as there was a change there so to push I had to change the .gitignore also

**Comment by grapheo12** [comment]
Yes remove `app.env`

**Comment by shobhit10058** [comment]
done

**Comment by shobhit10058** [comment]
@grapheo12 is there some error?

**Review by grapheo12 — APPROVED** [review]
Looks good as an initial work! Merging this. But you need to work more on the LOGIN_REQUIRED variable. It is passed but not used in the templates I see.

**Comment by shobhit10058** [comment]
is it not used? I have used them that is in the templates but I don't know why it is not working? Can you look once in the code and check the mistake

**Pull request merged**
