### PR TITLE
Add sanity script to comply with PEP8

### PR DESCRIPTION
**Pull request by mukul-mehta**
This PR adds a `sanity.sh` script that can be run to ensure there are no PEP8 errors. It uses the configurations defined in `.pycodestylerc` and `.pydocstylerc` to run checks.

### CODE REVIEW

**Comment by mukul-mehta** [comment]
@grapheo12 In `pycodestyle` settings, I've set the max line length parameter to be 120. Let's choose either 79 or 120 and then use that value for both `pep8speaks` and `pycodestyle`.

**Comment by grapheo12** [comment]
@mukul-mehta Can you please rebase your PR?
I've recently cleaned up most of the PEP8 issues in #16 .
Also let's keep the max line length to 120.
Can you add a .pep8speaks.yml file?

**Comment by mukul-mehta** [comment]
@grapheo12 Sure, I'll make the changes.

**Comment by grapheo12** [comment]
@mukul-mehta How to use this sanity.sh file? How to ensure it runs on every PR?

**Comment by mukul-mehta** [comment]
@grapheo12 For now, I'm using a pre-commit hook. I believe it would be a good idea to setup Travis or CircleCI to run the sanity script.

**Pull request closed without merging**
