### PR TITLE
Adding limits to year field / filter 

### LINKED ISSUE #5: Adding limits to year field / filter
Currently, we can assign any year to the papers (even future years like 2030 and ridiculously old times like 1) and also enter such absurd years as a search filter. Hence we need to limit the years to (1951-current), both in models and in frontend.

### PR DESCRIPTION
**Pull request by thealphadollar**
This PR, if merged, will add limits to the year field in all forms and models concerned.

P.S. Please test run the PR as I was not able to test on my system.

fixes #5

### CODE REVIEW

**Comment by thealphadollar** [comment]
@grapheo12 My advance apologies for this messy PR, I've not been able to get much time but I want to contribute and see this deployed ASAP. There are a few things you would need to do before merging this PR:

- Delete duplicate functions and import them from a commonplace (such as utils).
- Run and test that the code is working

Thank you.

**Comment by grapheo12** [comment]
@thealphadollar Can you specify why you weren't able to test it on your system?
I can fix the issue.

**Comment by thealphadollar** [comment]
Oh, I didn't have the time to setup everything for the test. There are no issues as such.

**Comment by grapheo12** [comment]
@thealphadollar I squashed all the commits and made slight changes. Will you please allow edit from maintainers option?

**Comment by grapheo12** [comment]
Thanks @thealphadollar for this amazing work.

**Pull request merged**
